name: Build and Test Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc

    - name: Install Python
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip

    - name: Install Verilator
      run: |
        sudo apt-get install -y verilator

    - name: Install Make
      run: |
        sudo apt-get install -y make

    - name: Run all standard simulation
      run: |
        make tests
        [ ! -s results/failed_tests.txt ] || (echo "One or more tests failed" && exit 1)

    ## Steps for running programs

    - name: Cache RISC-V Toolchain
      id: cache-riscv
      uses: actions/cache@v4
      with:
        path: riscv
        key: riscv-toolchain-v1

    - name: Download and extract RISC-V toolchain (if not cached)
      if: steps.cache-riscv.outputs.cache-hit != 'true'
      run: |
        echo "Downloading prebuilt toolchain..."
        wget https://github.com/MCR748/100line-processor/releases/download/riscv-toolchain/riscv-toolchain.tar.gz
        tar -xzf riscv-toolchain.tar.gz 
        rm riscv-toolchain.tar.gz

    - name: Run all algorithm tests
      run: ./algo_tests
